#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.0
#  in conjunction with Tcl version 8.6
#    Jan 04, 2022 12:42:20 PM CET  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import LogfileViewer

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = LogfileViewer.Toplevel1(_top1)
    root.mainloop()

def DisplaySelected(*args):
    print('LogfileViewer_support.DisplaySelected')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def open_Loader(*args):
    print('LogfileViewer_support.open_Loader')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

if __name__ == '__main__':
    LogfileViewer.start_up()




