#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Feb 07, 2020 07:51:43 AM CET  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Cell_control_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = toplevel (root)
    Cell_control_support.init(root, top)
    root.mainloop()

w = None
def create_toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = toplevel (w)
    Cell_control_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_toplevel():
    global w
    w.destroy()
    w = None

class toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("458x980+493+16")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.open1 = tk.Button(top)
        self.open1.place(relx=0.131, rely=0.163, height=64, width=67)
        self.open1.configure(activebackground="#ececec")
        self.open1.configure(activeforeground="#000000")
        self.open1.configure(background="#5b5b5b")
        self.open1.configure(disabledforeground="#a3a3a3")
        self.open1.configure(foreground="#000000")
        self.open1.configure(highlightbackground="#d9d9d9")
        self.open1.configure(highlightcolor="black")
        self.open1.configure(pady="0")
        self.open1.configure(text='''Open''')

        self.close1 = tk.Button(top)
        self.close1.place(relx=0.306, rely=0.163, height=64, width=67)
        self.close1.configure(activebackground="#ececec")
        self.close1.configure(activeforeground="#000000")
        self.close1.configure(background="#5b5b5b")
        self.close1.configure(disabledforeground="#a3a3a3")
        self.close1.configure(foreground="#000000")
        self.close1.configure(highlightbackground="#d9d9d9")
        self.close1.configure(highlightcolor="black")
        self.close1.configure(pady="0")
        self.close1.configure(text='''Close''')

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.022, rely=0.112, height=41, width=74)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 14")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Cell 1''')

        self.SetT1 = tk.Button(top)
        self.SetT1.place(relx=0.502, rely=0.265, height=24, width=67)
        self.SetT1.configure(activebackground="#ececec")
        self.SetT1.configure(activeforeground="#000000")
        self.SetT1.configure(background="#5b5b5b")
        self.SetT1.configure(cursor="fleur")
        self.SetT1.configure(disabledforeground="#a3a3a3")
        self.SetT1.configure(foreground="#000000")
        self.SetT1.configure(highlightbackground="#d9d9d9")
        self.SetT1.configure(highlightcolor="black")
        self.SetT1.configure(pady="0")
        self.SetT1.configure(text='''set''')

        self.Cell1_read = tk.Text(top)
        self.Cell1_read.place(relx=0.131, rely=0.265, relheight=0.024
                , relwidth=0.162)
        self.Cell1_read.configure(background="white")
        self.Cell1_read.configure(font="TkTextFont")
        self.Cell1_read.configure(foreground="black")
        self.Cell1_read.configure(highlightbackground="#d9d9d9")
        self.Cell1_read.configure(highlightcolor="black")
        self.Cell1_read.configure(insertbackground="black")
        self.Cell1_read.configure(selectbackground="#c4c4c4")
        self.Cell1_read.configure(selectforeground="black")
        self.Cell1_read.configure(wrap="word")

        self.Cell1_set = tk.Text(top)
        self.Cell1_set.place(relx=0.328, rely=0.265, relheight=0.024
                , relwidth=0.162)
        self.Cell1_set.configure(background="white")
        self.Cell1_set.configure(font="TkTextFont")
        self.Cell1_set.configure(foreground="black")
        self.Cell1_set.configure(highlightbackground="#d9d9d9")
        self.Cell1_set.configure(highlightcolor="black")
        self.Cell1_set.configure(insertbackground="black")
        self.Cell1_set.configure(selectbackground="#c4c4c4")
        self.Cell1_set.configure(selectforeground="black")
        self.Cell1_set.configure(wrap="word")

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.131, rely=0.235, height=21, width=39)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''T read''')

        self.Label2_4 = tk.Label(top)
        self.Label2_4.place(relx=0.328, rely=0.235, height=21, width=59)
        self.Label2_4.configure(activebackground="#f9f9f9")
        self.Label2_4.configure(activeforeground="black")
        self.Label2_4.configure(background="#d9d9d9")
        self.Label2_4.configure(disabledforeground="#a3a3a3")
        self.Label2_4.configure(foreground="#000000")
        self.Label2_4.configure(highlightbackground="#d9d9d9")
        self.Label2_4.configure(highlightcolor="black")
        self.Label2_4.configure(text='''Setpoint''')

        self.Label2_5 = tk.Label(top)
        self.Label2_5.place(relx=0.109, rely=0.306, height=21, width=79)
        self.Label2_5.configure(activebackground="#f9f9f9")
        self.Label2_5.configure(activeforeground="black")
        self.Label2_5.configure(background="#d9d9d9")
        self.Label2_5.configure(disabledforeground="#a3a3a3")
        self.Label2_5.configure(foreground="#000000")
        self.Label2_5.configure(highlightbackground="#d9d9d9")
        self.Label2_5.configure(highlightcolor="black")
        self.Label2_5.configure(text='''open since:''')

        self.Cell1_time = tk.Text(top)
        self.Cell1_time.place(relx=0.306, rely=0.306, relheight=0.024
                , relwidth=0.162)
        self.Cell1_time.configure(background="white")
        self.Cell1_time.configure(font="TkTextFont")
        self.Cell1_time.configure(foreground="black")
        self.Cell1_time.configure(highlightbackground="#d9d9d9")
        self.Cell1_time.configure(highlightcolor="black")
        self.Cell1_time.configure(insertbackground="black")
        self.Cell1_time.configure(selectbackground="#c4c4c4")
        self.Cell1_time.configure(selectforeground="black")
        self.Cell1_time.configure(wrap="word")

        self.Label1_7 = tk.Label(top)
        self.Label1_7.place(relx=0.044, rely=0.337, height=41, width=74)
        self.Label1_7.configure(activebackground="#f9f9f9")
        self.Label1_7.configure(activeforeground="black")
        self.Label1_7.configure(background="#d9d9d9")
        self.Label1_7.configure(disabledforeground="#a3a3a3")
        self.Label1_7.configure(font="-family {Segoe UI} -size 14")
        self.Label1_7.configure(foreground="#000000")
        self.Label1_7.configure(highlightbackground="#d9d9d9")
        self.Label1_7.configure(highlightcolor="black")
        self.Label1_7.configure(text='''Cell 2''')

        self.Label2_8 = tk.Label(top)
        self.Label2_8.place(relx=0.131, rely=0.5, height=21, width=39)
        self.Label2_8.configure(activebackground="#f9f9f9")
        self.Label2_8.configure(activeforeground="black")
        self.Label2_8.configure(background="#d9d9d9")
        self.Label2_8.configure(disabledforeground="#a3a3a3")
        self.Label2_8.configure(foreground="#000000")
        self.Label2_8.configure(highlightbackground="#d9d9d9")
        self.Label2_8.configure(highlightcolor="black")
        self.Label2_8.configure(text='''T read''')

        self.open2 = tk.Button(top)
        self.open2.place(relx=0.131, rely=0.378, height=64, width=67)
        self.open2.configure(activebackground="#ececec")
        self.open2.configure(activeforeground="#000000")
        self.open2.configure(background="#5b5b5b")
        self.open2.configure(disabledforeground="#a3a3a3")
        self.open2.configure(foreground="#000000")
        self.open2.configure(highlightbackground="#d9d9d9")
        self.open2.configure(highlightcolor="black")
        self.open2.configure(pady="0")
        self.open2.configure(text='''Open''')

        self.close2 = tk.Button(top)
        self.close2.place(relx=0.306, rely=0.378, height=64, width=67)
        self.close2.configure(activebackground="#ececec")
        self.close2.configure(activeforeground="#000000")
        self.close2.configure(background="#5b5b5b")
        self.close2.configure(disabledforeground="#a3a3a3")
        self.close2.configure(foreground="#000000")
        self.close2.configure(highlightbackground="#d9d9d9")
        self.close2.configure(highlightcolor="black")
        self.close2.configure(pady="0")
        self.close2.configure(text='''Close''')

        self.Button1_3 = tk.Button(top)
        self.Button1_3.place(relx=0.131, rely=0.449, height=24, width=27)
        self.Button1_3.configure(activebackground="#ececec")
        self.Button1_3.configure(activeforeground="#000000")
        self.Button1_3.configure(background="#5b5b5b")
        self.Button1_3.configure(disabledforeground="#a3a3a3")
        self.Button1_3.configure(foreground="#000000")
        self.Button1_3.configure(highlightbackground="#d9d9d9")
        self.Button1_3.configure(highlightcolor="black")
        self.Button1_3.configure(pady="0")
        self.Button1_3.configure(text='''1''')

        self.Button1_4 = tk.Button(top)
        self.Button1_4.place(relx=0.197, rely=0.449, height=24, width=27)
        self.Button1_4.configure(activebackground="#ececec")
        self.Button1_4.configure(activeforeground="#000000")
        self.Button1_4.configure(background="#5b5b5b")
        self.Button1_4.configure(disabledforeground="#a3a3a3")
        self.Button1_4.configure(foreground="#000000")
        self.Button1_4.configure(highlightbackground="#d9d9d9")
        self.Button1_4.configure(highlightcolor="black")
        self.Button1_4.configure(pady="0")
        self.Button1_4.configure(text='''2''')

        self.Button1_5 = tk.Button(top)
        self.Button1_5.place(relx=0.262, rely=0.449, height=24, width=27)
        self.Button1_5.configure(activebackground="#ececec")
        self.Button1_5.configure(activeforeground="#000000")
        self.Button1_5.configure(background="#5b5b5b")
        self.Button1_5.configure(disabledforeground="#a3a3a3")
        self.Button1_5.configure(foreground="#000000")
        self.Button1_5.configure(highlightbackground="#d9d9d9")
        self.Button1_5.configure(highlightcolor="black")
        self.Button1_5.configure(pady="0")
        self.Button1_5.configure(text='''3''')

        self.Button1_2 = tk.Button(top)
        self.Button1_2.place(relx=0.328, rely=0.449, height=24, width=27)
        self.Button1_2.configure(activebackground="#ececec")
        self.Button1_2.configure(activeforeground="#000000")
        self.Button1_2.configure(background="#5b5b5b")
        self.Button1_2.configure(disabledforeground="#a3a3a3")
        self.Button1_2.configure(foreground="#000000")
        self.Button1_2.configure(highlightbackground="#d9d9d9")
        self.Button1_2.configure(highlightcolor="black")
        self.Button1_2.configure(pady="0")
        self.Button1_2.configure(text='''4''')

        self.Button1_6 = tk.Button(top)
        self.Button1_6.place(relx=0.393, rely=0.449, height=24, width=27)
        self.Button1_6.configure(activebackground="#ececec")
        self.Button1_6.configure(activeforeground="#000000")
        self.Button1_6.configure(background="#5b5b5b")
        self.Button1_6.configure(disabledforeground="#a3a3a3")
        self.Button1_6.configure(foreground="#000000")
        self.Button1_6.configure(highlightbackground="#d9d9d9")
        self.Button1_6.configure(highlightcolor="black")
        self.Button1_6.configure(pady="0")
        self.Button1_6.configure(text='''1-2''')

        self.Cell2_11_read = tk.Text(top)
        self.Cell2_11_read.place(relx=0.24, rely=0.5, relheight=0.024
                , relwidth=0.162)
        self.Cell2_11_read.configure(background="white")
        self.Cell2_11_read.configure(font="TkTextFont")
        self.Cell2_11_read.configure(foreground="black")
        self.Cell2_11_read.configure(highlightbackground="#d9d9d9")
        self.Cell2_11_read.configure(highlightcolor="black")
        self.Cell2_11_read.configure(insertbackground="black")
        self.Cell2_11_read.configure(selectbackground="#c4c4c4")
        self.Cell2_11_read.configure(selectforeground="black")
        self.Cell2_11_read.configure(wrap="word")

        self.Cell2_2_read = tk.Text(top)
        self.Cell2_2_read.place(relx=0.24, rely=0.531, relheight=0.024
                , relwidth=0.162)
        self.Cell2_2_read.configure(background="white")
        self.Cell2_2_read.configure(font="TkTextFont")
        self.Cell2_2_read.configure(foreground="black")
        self.Cell2_2_read.configure(highlightbackground="#d9d9d9")
        self.Cell2_2_read.configure(highlightcolor="black")
        self.Cell2_2_read.configure(insertbackground="black")
        self.Cell2_2_read.configure(selectbackground="#c4c4c4")
        self.Cell2_2_read.configure(selectforeground="black")
        self.Cell2_2_read.configure(wrap="word")

        self.Cell2_3_read = tk.Text(top)
        self.Cell2_3_read.place(relx=0.24, rely=0.561, relheight=0.024
                , relwidth=0.162)
        self.Cell2_3_read.configure(background="white")
        self.Cell2_3_read.configure(font="TkTextFont")
        self.Cell2_3_read.configure(foreground="black")
        self.Cell2_3_read.configure(highlightbackground="#d9d9d9")
        self.Cell2_3_read.configure(highlightcolor="black")
        self.Cell2_3_read.configure(insertbackground="black")
        self.Cell2_3_read.configure(selectbackground="#c4c4c4")
        self.Cell2_3_read.configure(selectforeground="black")
        self.Cell2_3_read.configure(wrap="word")

        self.Cell2_4_read = tk.Text(top)
        self.Cell2_4_read.place(relx=0.24, rely=0.592, relheight=0.024
                , relwidth=0.162)
        self.Cell2_4_read.configure(background="white")
        self.Cell2_4_read.configure(font="TkTextFont")
        self.Cell2_4_read.configure(foreground="black")
        self.Cell2_4_read.configure(highlightbackground="#d9d9d9")
        self.Cell2_4_read.configure(highlightcolor="black")
        self.Cell2_4_read.configure(insertbackground="black")
        self.Cell2_4_read.configure(selectbackground="#c4c4c4")
        self.Cell2_4_read.configure(selectforeground="black")
        self.Cell2_4_read.configure(wrap="word")

        self.Label2_3 = tk.Label(top)
        self.Label2_3.place(relx=0.437, rely=0.5, height=21, width=59)
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(activeforeground="black")
        self.Label2_3.configure(background="#d9d9d9")
        self.Label2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_3.configure(foreground="#000000")
        self.Label2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_3.configure(highlightcolor="black")
        self.Label2_3.configure(text='''Setpoint''')

        self.Cell2_1_set = tk.Text(top)
        self.Cell2_1_set.place(relx=0.568, rely=0.5, relheight=0.024
                , relwidth=0.162)
        self.Cell2_1_set.configure(background="white")
        self.Cell2_1_set.configure(font="TkTextFont")
        self.Cell2_1_set.configure(foreground="black")
        self.Cell2_1_set.configure(highlightbackground="#d9d9d9")
        self.Cell2_1_set.configure(highlightcolor="black")
        self.Cell2_1_set.configure(insertbackground="black")
        self.Cell2_1_set.configure(selectbackground="#c4c4c4")
        self.Cell2_1_set.configure(selectforeground="black")
        self.Cell2_1_set.configure(wrap="word")

        self.Cell2_2_set = tk.Text(top)
        self.Cell2_2_set.place(relx=0.568, rely=0.531, relheight=0.024
                , relwidth=0.162)
        self.Cell2_2_set.configure(background="white")
        self.Cell2_2_set.configure(cursor="fleur")
        self.Cell2_2_set.configure(font="TkTextFont")
        self.Cell2_2_set.configure(foreground="black")
        self.Cell2_2_set.configure(highlightbackground="#d9d9d9")
        self.Cell2_2_set.configure(highlightcolor="black")
        self.Cell2_2_set.configure(insertbackground="black")
        self.Cell2_2_set.configure(selectbackground="#c4c4c4")
        self.Cell2_2_set.configure(selectforeground="black")
        self.Cell2_2_set.configure(wrap="word")

        self.Cell2_3_set = tk.Text(top)
        self.Cell2_3_set.place(relx=0.568, rely=0.561, relheight=0.024
                , relwidth=0.162)
        self.Cell2_3_set.configure(background="white")
        self.Cell2_3_set.configure(font="TkTextFont")
        self.Cell2_3_set.configure(foreground="black")
        self.Cell2_3_set.configure(highlightbackground="#d9d9d9")
        self.Cell2_3_set.configure(highlightcolor="black")
        self.Cell2_3_set.configure(insertbackground="black")
        self.Cell2_3_set.configure(selectbackground="#c4c4c4")
        self.Cell2_3_set.configure(selectforeground="black")
        self.Cell2_3_set.configure(wrap="word")

        self.Cell2_4_set = tk.Text(top)
        self.Cell2_4_set.place(relx=0.568, rely=0.592, relheight=0.024
                , relwidth=0.162)
        self.Cell2_4_set.configure(background="white")
        self.Cell2_4_set.configure(font="TkTextFont")
        self.Cell2_4_set.configure(foreground="black")
        self.Cell2_4_set.configure(highlightbackground="#d9d9d9")
        self.Cell2_4_set.configure(highlightcolor="black")
        self.Cell2_4_set.configure(insertbackground="black")
        self.Cell2_4_set.configure(selectbackground="#c4c4c4")
        self.Cell2_4_set.configure(selectforeground="black")
        self.Cell2_4_set.configure(wrap="word")

        self.setT21 = tk.Button(top)
        self.setT21.place(relx=0.764, rely=0.5, height=24, width=67)
        self.setT21.configure(activebackground="#ececec")
        self.setT21.configure(activeforeground="#000000")
        self.setT21.configure(background="#5b5b5b")
        self.setT21.configure(disabledforeground="#a3a3a3")
        self.setT21.configure(foreground="#000000")
        self.setT21.configure(highlightbackground="#d9d9d9")
        self.setT21.configure(highlightcolor="black")
        self.setT21.configure(pady="0")
        self.setT21.configure(text='''set''')

        self.setT22 = tk.Button(top)
        self.setT22.place(relx=0.764, rely=0.531, height=24, width=67)
        self.setT22.configure(activebackground="#ececec")
        self.setT22.configure(activeforeground="#000000")
        self.setT22.configure(background="#5b5b5b")
        self.setT22.configure(disabledforeground="#a3a3a3")
        self.setT22.configure(foreground="#000000")
        self.setT22.configure(highlightbackground="#d9d9d9")
        self.setT22.configure(highlightcolor="black")
        self.setT22.configure(pady="0")
        self.setT22.configure(text='''set''')

        self.setT2 = tk.Button(top)
        self.setT2.place(relx=0.764, rely=0.561, height=24, width=67)
        self.setT2.configure(activebackground="#ececec")
        self.setT2.configure(activeforeground="#000000")
        self.setT2.configure(background="#5b5b5b")
        self.setT2.configure(disabledforeground="#a3a3a3")
        self.setT2.configure(foreground="#000000")
        self.setT2.configure(highlightbackground="#d9d9d9")
        self.setT2.configure(highlightcolor="black")
        self.setT2.configure(pady="0")
        self.setT2.configure(text='''set''')

        self.setT24 = tk.Button(top)
        self.setT24.place(relx=0.764, rely=0.592, height=24, width=67)
        self.setT24.configure(activebackground="#ececec")
        self.setT24.configure(activeforeground="#000000")
        self.setT24.configure(background="#5b5b5b")
        self.setT24.configure(disabledforeground="#a3a3a3")
        self.setT24.configure(foreground="#000000")
        self.setT24.configure(highlightbackground="#d9d9d9")
        self.setT24.configure(highlightcolor="black")
        self.setT24.configure(pady="0")
        self.setT24.configure(text='''set''')

        self.Label2_6 = tk.Label(top)
        self.Label2_6.place(relx=0.109, rely=0.633, height=21, width=79)
        self.Label2_6.configure(activebackground="#f9f9f9")
        self.Label2_6.configure(activeforeground="black")
        self.Label2_6.configure(background="#d9d9d9")
        self.Label2_6.configure(disabledforeground="#a3a3a3")
        self.Label2_6.configure(foreground="#000000")
        self.Label2_6.configure(highlightbackground="#d9d9d9")
        self.Label2_6.configure(highlightcolor="black")
        self.Label2_6.configure(text='''open since:''')

        self.Text1_8 = tk.Text(top)
        self.Text1_8.place(relx=0.306, rely=0.633, relheight=0.024
                , relwidth=0.162)
        self.Text1_8.configure(background="white")
        self.Text1_8.configure(font="TkTextFont")
        self.Text1_8.configure(foreground="black")
        self.Text1_8.configure(highlightbackground="#d9d9d9")
        self.Text1_8.configure(highlightcolor="black")
        self.Text1_8.configure(insertbackground="black")
        self.Text1_8.configure(selectbackground="#c4c4c4")
        self.Text1_8.configure(selectforeground="black")
        self.Text1_8.configure(wrap="word")

        self.Button1_3 = tk.Button(top)
        self.Button1_3.place(relx=0.742, rely=0.01, height=24, width=107)
        self.Button1_3.configure(activebackground="#ececec")
        self.Button1_3.configure(activeforeground="#000000")
        self.Button1_3.configure(background="#5b5b5b")
        self.Button1_3.configure(disabledforeground="#a3a3a3")
        self.Button1_3.configure(foreground="#000000")
        self.Button1_3.configure(highlightbackground="#d9d9d9")
        self.Button1_3.configure(highlightcolor="black")
        self.Button1_3.configure(pady="0")
        self.Button1_3.configure(text='''menu''')

        self.Button1_4 = tk.Button(top)
        self.Button1_4.place(relx=0.742, rely=0.041, height=24, width=107)
        self.Button1_4.configure(activebackground="#ececec")
        self.Button1_4.configure(activeforeground="#000000")
        self.Button1_4.configure(background="#5b5b5b")
        self.Button1_4.configure(disabledforeground="#a3a3a3")
        self.Button1_4.configure(foreground="#000000")
        self.Button1_4.configure(highlightbackground="#d9d9d9")
        self.Button1_4.configure(highlightcolor="black")
        self.Button1_4.configure(pady="0")
        self.Button1_4.configure(text='''status check''')

        self.Stepper_status = tk.Text(top)
        self.Stepper_status.place(relx=0.873, rely=0.082, relheight=0.024
                , relwidth=0.096)
        self.Stepper_status.configure(background="white")
        self.Stepper_status.configure(font="TkTextFont")
        self.Stepper_status.configure(foreground="black")
        self.Stepper_status.configure(highlightbackground="#d9d9d9")
        self.Stepper_status.configure(highlightcolor="black")
        self.Stepper_status.configure(insertbackground="black")
        self.Stepper_status.configure(selectbackground="#c4c4c4")
        self.Stepper_status.configure(selectforeground="black")
        self.Stepper_status.configure(wrap="word")

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.742, rely=0.082, height=21, width=51)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Steppers''')

        self.Label3_5 = tk.Label(top)
        self.Label3_5.place(relx=0.742, rely=0.112, height=21, width=51)
        self.Label3_5.configure(activebackground="#f9f9f9")
        self.Label3_5.configure(activeforeground="black")
        self.Label3_5.configure(background="#d9d9d9")
        self.Label3_5.configure(disabledforeground="#a3a3a3")
        self.Label3_5.configure(foreground="#000000")
        self.Label3_5.configure(highlightbackground="#d9d9d9")
        self.Label3_5.configure(highlightcolor="black")
        self.Label3_5.configure(text='''PID s''')

        self.PIDs_Status = tk.Text(top)
        self.PIDs_Status.place(relx=0.873, rely=0.112, relheight=0.024
                , relwidth=0.096)
        self.PIDs_Status.configure(background="white")
        self.PIDs_Status.configure(font="TkTextFont")
        self.PIDs_Status.configure(foreground="black")
        self.PIDs_Status.configure(highlightbackground="#d9d9d9")
        self.PIDs_Status.configure(highlightcolor="black")
        self.PIDs_Status.configure(insertbackground="black")
        self.PIDs_Status.configure(selectbackground="#c4c4c4")
        self.PIDs_Status.configure(selectforeground="black")
        self.PIDs_Status.configure(wrap="word")

        self.ProgramPath = tk.Text(top)
        self.ProgramPath.place(relx=0.044, rely=0.724, relheight=0.024
                , relwidth=0.576)
        self.ProgramPath.configure(background="white")
        self.ProgramPath.configure(cursor="fleur")
        self.ProgramPath.configure(font="TkTextFont")
        self.ProgramPath.configure(foreground="black")
        self.ProgramPath.configure(highlightbackground="#d9d9d9")
        self.ProgramPath.configure(highlightcolor="black")
        self.ProgramPath.configure(insertbackground="black")
        self.ProgramPath.configure(selectbackground="#c4c4c4")
        self.ProgramPath.configure(selectforeground="black")
        self.ProgramPath.configure(wrap="word")

        self.selectPath = tk.Button(top)
        self.selectPath.place(relx=0.655, rely=0.724, height=24, width=67)
        self.selectPath.configure(activebackground="#ececec")
        self.selectPath.configure(activeforeground="#000000")
        self.selectPath.configure(background="#5b5b5b")
        self.selectPath.configure(disabledforeground="#a3a3a3")
        self.selectPath.configure(foreground="#000000")
        self.selectPath.configure(highlightbackground="#d9d9d9")
        self.selectPath.configure(highlightcolor="black")
        self.selectPath.configure(pady="0")
        self.selectPath.configure(text='''select''')

        self.Label1_8 = tk.Label(top)
        self.Label1_8.place(relx=0.044, rely=0.673, height=41, width=154)
        self.Label1_8.configure(activebackground="#f9f9f9")
        self.Label1_8.configure(activeforeground="black")
        self.Label1_8.configure(background="#d9d9d9")
        self.Label1_8.configure(disabledforeground="#a3a3a3")
        self.Label1_8.configure(font="-family {Segoe UI} -size 14")
        self.Label1_8.configure(foreground="#000000")
        self.Label1_8.configure(highlightbackground="#d9d9d9")
        self.Label1_8.configure(highlightcolor="black")
        self.Label1_8.configure(text='''Growth Program''')

        self.loadProgram = tk.Button(top)
        self.loadProgram.place(relx=0.83, rely=0.724, height=24, width=67)
        self.loadProgram.configure(activebackground="#ececec")
        self.loadProgram.configure(activeforeground="#000000")
        self.loadProgram.configure(background="#5b5b5b")
        self.loadProgram.configure(cursor="fleur")
        self.loadProgram.configure(disabledforeground="#a3a3a3")
        self.loadProgram.configure(foreground="#000000")
        self.loadProgram.configure(highlightbackground="#d9d9d9")
        self.loadProgram.configure(highlightcolor="black")
        self.loadProgram.configure(pady="0")
        self.loadProgram.configure(text='''load''')

        self.program_prev = ScrolledText(top)
        self.program_prev.place(relx=0.153, rely=0.765, relheight=0.103
                , relwidth=0.57)
        self.program_prev.configure(background="white")
        self.program_prev.configure(font="TkTextFont")
        self.program_prev.configure(foreground="black")
        self.program_prev.configure(highlightbackground="#d9d9d9")
        self.program_prev.configure(highlightcolor="black")
        self.program_prev.configure(insertbackground="black")
        self.program_prev.configure(insertborderwidth="3")
        self.program_prev.configure(selectbackground="#c4c4c4")
        self.program_prev.configure(selectforeground="black")
        self.program_prev.configure(wrap="none")

        self.Program_status = ScrolledText(top)
        self.Program_status.place(relx=0.153, rely=0.878, relheight=0.103
                , relwidth=0.57)
        self.Program_status.configure(background="white")
        self.Program_status.configure(font="TkTextFont")
        self.Program_status.configure(foreground="black")
        self.Program_status.configure(highlightbackground="#d9d9d9")
        self.Program_status.configure(highlightcolor="black")
        self.Program_status.configure(insertbackground="black")
        self.Program_status.configure(insertborderwidth="3")
        self.Program_status.configure(selectbackground="#c4c4c4")
        self.Program_status.configure(selectforeground="black")
        self.Program_status.configure(wrap="none")

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.022, rely=0.765, height=21, width=52)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Program''')

        self.Label4_12 = tk.Label(top)
        self.Label4_12.place(relx=0.022, rely=0.878, height=21, width=52)
        self.Label4_12.configure(activebackground="#f9f9f9")
        self.Label4_12.configure(activeforeground="black")
        self.Label4_12.configure(background="#d9d9d9")
        self.Label4_12.configure(disabledforeground="#a3a3a3")
        self.Label4_12.configure(foreground="#000000")
        self.Label4_12.configure(highlightbackground="#d9d9d9")
        self.Label4_12.configure(highlightcolor="black")
        self.Label4_12.configure(text='''Status''')

        self.runprogram = tk.Button(top)
        self.runprogram.place(relx=0.764, rely=0.765, height=64, width=67)
        self.runprogram.configure(activebackground="#ececec")
        self.runprogram.configure(activeforeground="#000000")
        self.runprogram.configure(background="#5b5b5b")
        self.runprogram.configure(disabledforeground="#a3a3a3")
        self.runprogram.configure(foreground="#000000")
        self.runprogram.configure(highlightbackground="#d9d9d9")
        self.runprogram.configure(highlightcolor="black")
        self.runprogram.configure(pady="0")
        self.runprogram.configure(text='''run''')

        self.pauseProgram = tk.Button(top)
        self.pauseProgram.place(relx=0.764, rely=0.837, height=24, width=67)
        self.pauseProgram.configure(activebackground="#ececec")
        self.pauseProgram.configure(activeforeground="#000000")
        self.pauseProgram.configure(background="#5b5b5b")
        self.pauseProgram.configure(cursor="fleur")
        self.pauseProgram.configure(disabledforeground="#a3a3a3")
        self.pauseProgram.configure(foreground="#000000")
        self.pauseProgram.configure(highlightbackground="#d9d9d9")
        self.pauseProgram.configure(highlightcolor="black")
        self.pauseProgram.configure(pady="0")
        self.pauseProgram.configure(text='''pause''')

        self.stopProgram = tk.Button(top)
        self.stopProgram.place(relx=0.764, rely=0.867, height=64, width=67)
        self.stopProgram.configure(activebackground="#ececec")
        self.stopProgram.configure(activeforeground="#000000")
        self.stopProgram.configure(background="#5b5b5b")
        self.stopProgram.configure(disabledforeground="#a3a3a3")
        self.stopProgram.configure(foreground="#000000")
        self.stopProgram.configure(highlightbackground="#d9d9d9")
        self.stopProgram.configure(highlightcolor="black")
        self.stopProgram.configure(pady="0")
        self.stopProgram.configure(text='''STOP''')

        self.Label1_13 = tk.Label(top)
        self.Label1_13.place(relx=0.022, rely=0.01, height=41, width=74)
        self.Label1_13.configure(activebackground="#f9f9f9")
        self.Label1_13.configure(activeforeground="black")
        self.Label1_13.configure(background="#d9d9d9")
        self.Label1_13.configure(disabledforeground="#a3a3a3")
        self.Label1_13.configure(font="-family {Segoe UI} -size 14")
        self.Label1_13.configure(foreground="#000000")
        self.Label1_13.configure(highlightbackground="#d9d9d9")
        self.Label1_13.configure(highlightcolor="black")
        self.Label1_13.configure(text='''Sample''')

        self.Label2_14 = tk.Label(top)
        self.Label2_14.place(relx=0.109, rely=0.051, height=21, width=39)
        self.Label2_14.configure(activebackground="#f9f9f9")
        self.Label2_14.configure(activeforeground="black")
        self.Label2_14.configure(background="#d9d9d9")
        self.Label2_14.configure(disabledforeground="#a3a3a3")
        self.Label2_14.configure(foreground="#000000")
        self.Label2_14.configure(highlightbackground="#d9d9d9")
        self.Label2_14.configure(highlightcolor="black")
        self.Label2_14.configure(text='''T read''')

        self.T_sample = tk.Text(top)
        self.T_sample.place(relx=0.109, rely=0.071, relheight=0.024
                , relwidth=0.162)
        self.T_sample.configure(background="white")
        self.T_sample.configure(font="TkTextFont")
        self.T_sample.configure(foreground="black")
        self.T_sample.configure(highlightbackground="#d9d9d9")
        self.T_sample.configure(highlightcolor="black")
        self.T_sample.configure(insertbackground="black")
        self.T_sample.configure(selectbackground="#c4c4c4")
        self.T_sample.configure(selectforeground="black")
        self.T_sample.configure(wrap="word")

        self.Label2_5 = tk.Label(top)
        self.Label2_5.place(relx=0.306, rely=0.051, height=21, width=59)
        self.Label2_5.configure(activebackground="#f9f9f9")
        self.Label2_5.configure(activeforeground="black")
        self.Label2_5.configure(background="#d9d9d9")
        self.Label2_5.configure(disabledforeground="#a3a3a3")
        self.Label2_5.configure(foreground="#000000")
        self.Label2_5.configure(highlightbackground="#d9d9d9")
        self.Label2_5.configure(highlightcolor="black")
        self.Label2_5.configure(text='''Setpoint''')

        self.SampleSetpoint = tk.Text(top)
        self.SampleSetpoint.place(relx=0.306, rely=0.071, relheight=0.024
                , relwidth=0.162)
        self.SampleSetpoint.configure(background="white")
        self.SampleSetpoint.configure(font="TkTextFont")
        self.SampleSetpoint.configure(foreground="black")
        self.SampleSetpoint.configure(highlightbackground="#d9d9d9")
        self.SampleSetpoint.configure(highlightcolor="black")
        self.SampleSetpoint.configure(insertbackground="black")
        self.SampleSetpoint.configure(selectbackground="#c4c4c4")
        self.SampleSetpoint.configure(selectforeground="black")
        self.SampleSetpoint.configure(wrap="word")

        self.set_substrateT = tk.Button(top)
        self.set_substrateT.place(relx=0.48, rely=0.071, height=24, width=67)
        self.set_substrateT.configure(activebackground="#ececec")
        self.set_substrateT.configure(activeforeground="#000000")
        self.set_substrateT.configure(background="#5b5b5b")
        self.set_substrateT.configure(disabledforeground="#a3a3a3")
        self.set_substrateT.configure(foreground="#000000")
        self.set_substrateT.configure(highlightbackground="#d9d9d9")
        self.set_substrateT.configure(highlightcolor="black")
        self.set_substrateT.configure(pady="0")
        self.set_substrateT.configure(text='''set''')

        self.Label3_4 = tk.Label(top)
        self.Label3_4.place(relx=0.742, rely=0.143, height=21, width=51)
        self.Label3_4.configure(activebackground="#f9f9f9")
        self.Label3_4.configure(activeforeground="black")
        self.Label3_4.configure(background="#d9d9d9")
        self.Label3_4.configure(cursor="fleur")
        self.Label3_4.configure(disabledforeground="#a3a3a3")
        self.Label3_4.configure(foreground="#000000")
        self.Label3_4.configure(highlightbackground="#d9d9d9")
        self.Label3_4.configure(highlightcolor="black")
        self.Label3_4.configure(text='''PID 1''')

        self.Label3_5 = tk.Label(top)
        self.Label3_5.place(relx=0.742, rely=0.173, height=21, width=51)
        self.Label3_5.configure(activebackground="#f9f9f9")
        self.Label3_5.configure(activeforeground="black")
        self.Label3_5.configure(background="#d9d9d9")
        self.Label3_5.configure(disabledforeground="#a3a3a3")
        self.Label3_5.configure(foreground="#000000")
        self.Label3_5.configure(highlightbackground="#d9d9d9")
        self.Label3_5.configure(highlightcolor="black")
        self.Label3_5.configure(text='''PID 2''')

        self.PID1_Status = tk.Text(top)
        self.PID1_Status.place(relx=0.873, rely=0.143, relheight=0.024
                , relwidth=0.096)
        self.PID1_Status.configure(background="white")
        self.PID1_Status.configure(font="TkTextFont")
        self.PID1_Status.configure(foreground="black")
        self.PID1_Status.configure(highlightbackground="#d9d9d9")
        self.PID1_Status.configure(highlightcolor="black")
        self.PID1_Status.configure(insertbackground="black")
        self.PID1_Status.configure(selectbackground="#c4c4c4")
        self.PID1_Status.configure(selectforeground="black")
        self.PID1_Status.configure(wrap="word")

        self.PID2_Status = tk.Text(top)
        self.PID2_Status.place(relx=0.873, rely=0.173, relheight=0.024
                , relwidth=0.096)
        self.PID2_Status.configure(background="white")
        self.PID2_Status.configure(font="TkTextFont")
        self.PID2_Status.configure(foreground="black")
        self.PID2_Status.configure(highlightbackground="#d9d9d9")
        self.PID2_Status.configure(highlightcolor="black")
        self.PID2_Status.configure(insertbackground="black")
        self.PID2_Status.configure(selectbackground="#c4c4c4")
        self.PID2_Status.configure(selectforeground="black")
        self.PID2_Status.configure(wrap="word")

        self.TSeparator1 = ttk.Separator(top)
        self.TSeparator1.place(relx=0.044, rely=0.673, relwidth=0.917)

        self.TSeparator1_8 = ttk.Separator(top)
        self.TSeparator1_8.place(relx=0.044, rely=0.337, relwidth=0.917)

        self.TSeparator1_9 = ttk.Separator(top)
        self.TSeparator1_9.place(relx=0.044, rely=0.112, relwidth=0.633)

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, tk.Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





