#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Aug 09, 2020 01:36:08 AM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import MainControl_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    MainControl_support.set_Tk_var()
    top = Toplevel1 (root)
    MainControl_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    #w = tk.Toplevel (root)
    MainControl_support.set_Tk_var()
    top = Toplevel1 (root)
    MainControl_support.init(root, top, *args, **kwargs)
    return (top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Segoe UI} -size 12"
        font9 = "-family {Segoe UI} -size 14"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("252x606+602+157")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Caption = tk.Label(top)
        self.Caption.place(relx=0.119, rely=0.017, height=62, width=204)
        self.Caption.configure(activebackground="#f9f9f9")
        self.Caption.configure(activeforeground="black")
        self.Caption.configure(background="#d9d9d9")
        self.Caption.configure(disabledforeground="#a3a3a3")
        self.Caption.configure(font="-family {Comic Sans MS} -size 18")
        self.Caption.configure(foreground="#000000")
        self.Caption.configure(highlightbackground="#d9d9d9")
        self.Caption.configure(highlightcolor="black")
        self.Caption.configure(text='''Watcha wanna do?''')

        self.Pressures = tk.Button(top)
        self.Pressures.place(relx=0.079, rely=0.149, height=44, width=207)
        self.Pressures.configure(activebackground="#ececec")
        self.Pressures.configure(activeforeground="#000000")
        self.Pressures.configure(background="#5f5f5f")
        self.Pressures.configure(command=MainControl_support.CallPressureWindow)
        self.Pressures.configure(disabledforeground="#a3a3a3")
        self.Pressures.configure(font="-family {Segoe UI} -size 14")
        self.Pressures.configure(foreground="#000000")
        self.Pressures.configure(highlightbackground="#d9d9d9")
        self.Pressures.configure(highlightcolor="black")
        self.Pressures.configure(pady="0")
        self.Pressures.configure(text='''Pressures''')

        self.ManiControl = tk.Button(top)
        self.ManiControl.place(relx=0.079, rely=0.248, height=44, width=207)
        self.ManiControl.configure(activebackground="#ececec")
        self.ManiControl.configure(activeforeground="#000000")
        self.ManiControl.configure(background="#5f5f5f")
        self.ManiControl.configure(command=MainControl_support.CallManiControlWindow)
        self.ManiControl.configure(disabledforeground="#a3a3a3")
        self.ManiControl.configure(font="-family {Segoe UI} -size 14")
        self.ManiControl.configure(foreground="#000000")
        self.ManiControl.configure(highlightbackground="#d9d9d9")
        self.ManiControl.configure(highlightcolor="black")
        self.ManiControl.configure(pady="0")
        self.ManiControl.configure(text='''Manipulator Control''')

        self.GrowthControl = tk.Button(top)
        self.GrowthControl.place(relx=0.079, rely=0.347, height=44, width=207)
        self.GrowthControl.configure(activebackground="#ececec")
        self.GrowthControl.configure(activeforeground="#000000")
        self.GrowthControl.configure(background="#5f5f5f")
        self.GrowthControl.configure(command=MainControl_support.CallGrowthWindow)
        self.GrowthControl.configure(disabledforeground="#a3a3a3")
        self.GrowthControl.configure(font="-family {Segoe UI} -size 14")
        self.GrowthControl.configure(foreground="#000000")
        self.GrowthControl.configure(highlightbackground="#d9d9d9")
        self.GrowthControl.configure(highlightcolor="black")
        self.GrowthControl.configure(pady="0")
        self.GrowthControl.configure(text='''Growth Control''')

        self.Remote = tk.Button(top)
        self.Remote.place(relx=0.079, rely=0.66, height=44, width=157)
        self.Remote.configure(activebackground="#ececec")
        self.Remote.configure(activeforeground="#000000")
        self.Remote.configure(background="#5f5f5f")
        self.Remote.configure(command=MainControl_support.EnableRemoteControl)
        self.Remote.configure(disabledforeground="#a3a3a3")
        self.Remote.configure(font="-family {Segoe UI} -size 14")
        self.Remote.configure(foreground="#000000")
        self.Remote.configure(highlightbackground="#d9d9d9")
        self.Remote.configure(highlightcolor="black")
        self.Remote.configure(pady="0")
        self.Remote.configure(text='''Remote enable''')

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.754, rely=0.66, relheight=0.074, relwidth=0.179)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#80ff00")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Mapping = tk.Button(top)
        self.Mapping.place(relx=0.079, rely=0.446, height=44, width=207)
        self.Mapping.configure(activebackground="#ececec")
        self.Mapping.configure(activeforeground="#000000")
        self.Mapping.configure(background="#5f5f5f")
        self.Mapping.configure(command=MainControl_support.CallMappingWindow)
        self.Mapping.configure(disabledforeground="#a3a3a3")
        self.Mapping.configure(font="-family {Segoe UI} -size 14")
        self.Mapping.configure(foreground="#000000")
        self.Mapping.configure(highlightbackground="#d9d9d9")
        self.Mapping.configure(highlightcolor="black")
        self.Mapping.configure(pady="0")
        self.Mapping.configure(text='''Mapping''')

        self.Load = tk.Button(top)
        self.Load.place(relx=0.079, rely=0.891, height=44, width=87)
        self.Load.configure(activebackground="#ececec")
        self.Load.configure(activeforeground="#000000")
        self.Load.configure(background="#5f5f5f")
        self.Load.configure(command=MainControl_support.LoadOld)
        self.Load.configure(disabledforeground="#a3a3a3")
        self.Load.configure(font="-family {Segoe UI} -size 14")
        self.Load.configure(foreground="#000000")
        self.Load.configure(highlightbackground="#d9d9d9")
        self.Load.configure(highlightcolor="black")
        self.Load.configure(pady="0")
        self.Load.configure(text='''Load''')

        self.Save = tk.Button(top)
        self.Save.place(relx=0.556, rely=0.891, height=44, width=87)
        self.Save.configure(activebackground="#ececec")
        self.Save.configure(activeforeground="#000000")
        self.Save.configure(background="#5f5f5f")
        self.Save.configure(command=MainControl_support.SaveStatus)
        self.Save.configure(disabledforeground="#a3a3a3")
        self.Save.configure(font="-family {Segoe UI} -size 14")
        self.Save.configure(foreground="#000000")
        self.Save.configure(highlightbackground="#d9d9d9")
        self.Save.configure(highlightcolor="black")
        self.Save.configure(pady="0")
        self.Save.configure(text='''Save''')

        self.Settings = tk.Button(top)
        self.Settings.place(relx=0.079, rely=0.792, height=44, width=207)
        self.Settings.configure(activebackground="#ececec")
        self.Settings.configure(activeforeground="#000000")
        self.Settings.configure(background="#5f5f5f")
        self.Settings.configure(command=MainControl_support.CallSettingsWindow)
        self.Settings.configure(disabledforeground="#a3a3a3")
        self.Settings.configure(font="-family {Segoe UI} -size 14")
        self.Settings.configure(foreground="#000000")
        self.Settings.configure(highlightbackground="#d9d9d9")
        self.Settings.configure(highlightcolor="black")
        self.Settings.configure(pady="0")
        self.Settings.configure(text='''Settings''')

        self.TSeparator1 = ttk.Separator(top)
        self.TSeparator1.place(relx=0.079, rely=0.627, relwidth=0.794)

        self.TSeparator2 = ttk.Separator(top)
        self.TSeparator2.place(relx=0.119, rely=0.759, relwidth=0.794)

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.startbutton = tk.Button(top)
        self.startbutton.place(relx=0.675, rely=0.545, height=44, width=57)
        self.startbutton.configure(activebackground="#ececec")
        self.startbutton.configure(activeforeground="#000000")
        self.startbutton.configure(background="#5f5f5f")
        self.startbutton.configure(command=MainControl_support.StartFlexicommand)
        self.startbutton.configure(disabledforeground="#a3a3a3")
        self.startbutton.configure(font=font9)
        self.startbutton.configure(foreground="#000000")
        self.startbutton.configure(highlightbackground="#d9d9d9")
        self.startbutton.configure(highlightcolor="black")
        self.startbutton.configure(pady="0")
        self.startbutton.configure(text='''Start''')

        self.Flexibox = ttk.Combobox(top)
        self.Flexibox.place(relx=0.119, rely=0.545, relheight=0.068
                , relwidth=0.528)
        self.Flexibox.configure(font=font10)
        self.Flexibox.configure(textvariable=MainControl_support.combobox)
        self.Flexibox.configure(takefocus="")

if __name__ == '__main__':
    vp_start_gui()





