#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Aug 09, 2020 01:36:04 AM CEST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m58" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 252x606+602+157
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 18} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Watcha wanna do?} 
    vTcl:DefineAlias "$top.lab43" "Caption" vTcl:WidgetProc "Toplevel1" 1
    button $top.but44 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -command CallPressureWindow \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Pressures 
    vTcl:DefineAlias "$top.but44" "Pressures" vTcl:WidgetProc "Toplevel1" 1
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -command CallManiControlWindow \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Manipulator Control} 
    vTcl:DefineAlias "$top.but46" "ManiControl" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -command CallGrowthWindow \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Growth Control} 
    vTcl:DefineAlias "$top.but47" "GrowthControl" vTcl:WidgetProc "Toplevel1" 1
    button $top.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -command EnableRemoteControl \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Remote enable} 
    vTcl:DefineAlias "$top.but49" "Remote" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra50 \
        -borderwidth 2 -relief groove -background #80ff00 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$top.fra50" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -command CallMappingWindow \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Mapping 
    vTcl:DefineAlias "$top.but51" "Mapping" vTcl:WidgetProc "Toplevel1" 1
    button $top.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -command LoadOld -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Load 
    vTcl:DefineAlias "$top.but52" "Load" vTcl:WidgetProc "Toplevel1" 1
    button $top.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -command SaveStatus -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Save 
    vTcl:DefineAlias "$top.but53" "Save" vTcl:WidgetProc "Toplevel1" 1
    button $top.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -command CallSettingsWindow \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Settings 
    vTcl:DefineAlias "$top.but55" "Settings" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe56
    vTcl:DefineAlias "$top.tSe56" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe57
    vTcl:DefineAlias "$top.tSe57" "TSeparator2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.m58
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    button $top.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -command StartFlexicommand \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Start 
    vTcl:DefineAlias "$top.but45" "startbutton" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo47 \
        -font {-family {Segoe UI} -size 12} -textvariable combobox \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo47" "Flexibox" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 0 -relx 0.119 -y 0 -rely 0.017 -width 0 -relwidth 0.81 \
        -height 0 -relheight 0.102 -anchor nw -bordermode ignore 
    place $top.but44 \
        -in $top -x 20 -y 90 -width 207 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 20 -y 150 -width 207 -height 44 -anchor nw \
        -bordermode ignore 
    place $top.but47 \
        -in $top -x 20 -y 210 -width 207 -height 44 -anchor nw \
        -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.079 -y 0 -rely 0.66 -width 157 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra50 \
        -in $top -x 0 -relx 0.754 -y 0 -rely 0.66 -width 0 -relwidth 0.179 \
        -height 0 -relheight 0.074 -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 20 -y 270 -width 207 -height 44 -anchor nw \
        -bordermode ignore 
    place $top.but52 \
        -in $top -x 20 -y 540 -width 87 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 140 -y 540 -width 87 -height 44 -anchor nw \
        -bordermode ignore 
    place $top.but55 \
        -in $top -x 20 -y 480 -width 207 -height 44 -anchor nw \
        -bordermode ignore 
    place $top.tSe56 \
        -in $top -x 0 -relx 0.079 -y 0 -rely 0.627 -width 0 -relwidth 0.794 \
        -anchor nw -bordermode inside 
    place $top.tSe57 \
        -in $top -x 0 -relx 0.119 -y 0 -rely 0.759 -width 0 -relwidth 0.794 \
        -height 2 -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 0 -relx 0.675 -y 0 -rely 0.545 -width 57 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tCo47 \
        -in $top -x 0 -relx 0.119 -y 0 -rely 0.545 -width 0 -relwidth 0.528 \
        -height 0 -relheight 0.068 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

