#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Mar 20, 2020 09:20:05 PM CET  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m51" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 582x349+415+134
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 16} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Mr Map} 
    vTcl:DefineAlias "$top.lab43" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 12} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text x 
    vTcl:DefineAlias "$top.lab50" "Label2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.m51
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    label $top.lab52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 12} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text y 
    vTcl:DefineAlias "$top.lab52" "Label2_4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 12} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text z 
    vTcl:DefineAlias "$top.lab53" "Label2_5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 12} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text theta 
    vTcl:DefineAlias "$top.lab54" "Label2_6" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo61 \
        -values 'fix','follow','map' {} -font TkTextFont \
        -textvariable combobox_x -validatecommand updateGUI -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo61" "xCombo" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo71 \
        -values 'fix','follow','map' {} -font TkTextFont \
        -textvariable combobox_y -validatecommand updateGUI -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo71" "yCombo" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo72 \
        -values 'fix','follow','map' {} -font TkTextFont \
        -textvariable combobox_z -validatecommand updateGUI -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo72" "zCombo" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo73 \
        -values 'fix','follow','map' {} -font TkTextFont \
        -textvariable combobox_th -validatecommand updateGUI -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo73" "tCombo" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab87 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 12} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text start 
    vTcl:DefineAlias "$top.lab87" "Label2_15" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab88 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 12} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text step 
    vTcl:DefineAlias "$top.lab88" "Label2_16" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab89 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 12} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text end 
    vTcl:DefineAlias "$top.lab89" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab90 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 12} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text N 
    vTcl:DefineAlias "$top.lab90" "Label2_17" vTcl:WidgetProc "Toplevel1" 1
    button $top.but95 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -command StartMap -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Start 
    vTcl:DefineAlias "$top.but95" "Start" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab97 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 12} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Sum 
    vTcl:DefineAlias "$top.lab97" "Label2_18" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent99 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable start_x -validate focusout \
        -validatecommand updateGUI 
    vTcl:DefineAlias "$top.ent99" "startx" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent100 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable step_x -validate focusout \
        -validatecommand updateGUI 
    vTcl:DefineAlias "$top.ent100" "stepx" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent101 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable end_x -validate focusout \
        -validatecommand updateGUI 
    vTcl:DefineAlias "$top.ent101" "endx" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent103 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable N_x -validate focusout \
        -validatecommand updateGUIN 
    vTcl:DefineAlias "$top.ent103" "Nx" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent104 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable start_y -validate focusout \
        -validatecommand updateGUI 
    vTcl:DefineAlias "$top.ent104" "starty" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent105 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable step_y -validate focusout \
        -validatecommand updateGUI 
    vTcl:DefineAlias "$top.ent105" "stepy" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent106 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable end_y -validate focusout \
        -validatecommand updateGUI 
    vTcl:DefineAlias "$top.ent106" "endy" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent107 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable N_y -validate focusout \
        -validatecommand updateGUIN 
    vTcl:DefineAlias "$top.ent107" "Ny" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent108 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable N_z -validate focusout \
        -validatecommand updateGUIN 
    vTcl:DefineAlias "$top.ent108" "Nz" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent109 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable end_z -validate focusout \
        -validatecommand updateGUI 
    vTcl:DefineAlias "$top.ent109" "endz" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent110 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable step_z -validate focusout \
        -validatecommand updateGUI 
    vTcl:DefineAlias "$top.ent110" "stepz" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent111 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable start_z -validate focusout \
        -validatecommand updateGUI 
    vTcl:DefineAlias "$top.ent111" "startz" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent112 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable start_t -validate focusout \
        -validatecommand updateGUI 
    vTcl:DefineAlias "$top.ent112" "startt" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent113 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable step_t -validate focusout \
        -validatecommand updateGUI 
    vTcl:DefineAlias "$top.ent113" "stept" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent114 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable end_t -validate focusout \
        -validatecommand updateGUI 
    vTcl:DefineAlias "$top.ent114" "endt" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent115 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable N_t -validate focusout \
        -validatecommand updateGUIN 
    vTcl:DefineAlias "$top.ent115" "Nt" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent116 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable Sum -validate focusout \
        -validatecommand updateGUI 
    vTcl:DefineAlias "$top.ent116" "Sum" vTcl:WidgetProc "Toplevel1" 1
    button $top.but117 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -command PauseMap -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Pause 
    vTcl:DefineAlias "$top.but117" "Pause" vTcl:WidgetProc "Toplevel1" 1
    button $top.but118 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ff0000 -command AbortMap -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text STOP 
    vTcl:DefineAlias "$top.but118" "Pause_23" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent119 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable folderpath 
    vTcl:DefineAlias "$top.ent119" "FolderPath" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab120 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 12} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Folder 
    vTcl:DefineAlias "$top.lab120" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but121 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -command CallFolderGrabber \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text get 
    vTcl:DefineAlias "$top.but121" "getFolder" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab122 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 12} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Status 
    vTcl:DefineAlias "$top.lab122" "Label2_8" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab123 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 12} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text ini 
    vTcl:DefineAlias "$top.lab123" "Label2_9" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo43 \
        -values 't','x','y','z' -font TkTextFont -textvariable main_ax \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo43" "mainAx" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Main axis} 
    vTcl:DefineAlias "$top.lab44" "Label3" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton $top.tCh43 \
        -variable relative_mapping -takefocus {} -text {relative mapping} 
    vTcl:DefineAlias "$top.tCh43" "RelMapChk" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 10 -y 10 -width 144 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 30 -y 90 -width 25 -relwidth 0 -height 39 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 30 -y 130 -width 25 -height 39 -anchor nw \
        -bordermode ignore 
    place $top.lab53 \
        -in $top -x 30 -y 170 -width 25 -height 39 -anchor nw \
        -bordermode ignore 
    place $top.lab54 \
        -in $top -x 10 -y 210 -width 45 -relwidth 0 -height 39 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo61 \
        -in $top -x 70 -y 100 -width 73 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo71 \
        -in $top -x 70 -y 140 -width 73 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo72 \
        -in $top -x 70 -y 180 -width 73 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo73 \
        -in $top -x 70 -y 220 -width 73 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab87 \
        -in $top -x 170 -y 60 -width 45 -relwidth 0 -height 39 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab88 \
        -in $top -x 250 -y 60 -width 45 -height 39 -anchor nw \
        -bordermode ignore 
    place $top.lab89 \
        -in $top -x 330 -y 60 -width 45 -height 39 -anchor nw \
        -bordermode ignore 
    place $top.lab90 \
        -in $top -x 400 -y 60 -width 45 -height 39 -anchor nw \
        -bordermode ignore 
    place $top.but95 \
        -in $top -x 500 -y 100 -anchor nw -bordermode ignore 
    place $top.lab97 \
        -in $top -x 340 -y 250 -width 45 -height 39 -anchor nw \
        -bordermode ignore 
    place $top.ent99 \
        -in $top -x 160 -y 100 -width 64 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent100 \
        -in $top -x 240 -y 100 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent101 \
        -in $top -x 320 -y 100 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent103 \
        -in $top -x 400 -y 100 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent104 \
        -in $top -x 160 -y 140 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent105 \
        -in $top -x 240 -y 140 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent106 \
        -in $top -x 320 -y 140 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent107 \
        -in $top -x 400 -y 140 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent108 \
        -in $top -x 400 -y 180 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent109 \
        -in $top -x 320 -y 180 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent110 \
        -in $top -x 240 -y 180 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent111 \
        -in $top -x 160 -y 180 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent112 \
        -in $top -x 160 -y 220 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent113 \
        -in $top -x 240 -y 220 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent114 \
        -in $top -x 320 -y 220 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent115 \
        -in $top -x 400 -y 220 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent116 \
        -in $top -x 400 -y 260 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.but117 \
        -in $top -x 500 -y 140 -width 35 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but118 \
        -in $top -x 500 -y 180 -width 35 -relwidth 0 -height 34 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent119 \
        -in $top -x 90 -y 310 -width 364 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab120 \
        -in $top -x 30 -y 300 -width 55 -relwidth 0 -height 39 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but121 \
        -in $top -x 460 -y 310 -width 35 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.lab122 \
        -in $top -x 510 -y 240 -width 55 -relwidth 0 -height 39 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab123 \
        -in $top -x 510 -y 270 -width 55 -relwidth 0 -height 29 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo43 \
        -in $top -x 240 -y 30 -width 33 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 170 -y 30 -anchor nw -bordermode ignore 
    place $top.tCh43 \
        -in $top -x 80 -y 260 -width 122 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

