#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Jun 10, 2020 06:37:18 PM CEST  platform: Windows NT

import sys
from PIL import ImageTk, Image

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    root.after(1, insertpic)


def insertpic():
    img = tk.PhotoImage(file='.\\Graphics\\Graphics_optics.png')
    w.Infographic = tk.Label(w.Canvas1,image=img)
    w.Infographic.photo = img
    w.Infographic.pack()
    #canvasimage = w.Canvas1.create_image(250, 250, image=img)
    #w.Canvas1.itemconfigure(image=canvasimage)
    #w.Canvas1.update_idletasks
    #root.update()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Optics_Control
    Optics_Control.vp_start_gui()




