#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Jun 10, 2020 07:32:14 PM CEST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m90" -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 945x391+603+239
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1173
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    canvas $top.can44 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 350 -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 407 
    vTcl:DefineAlias "$top.can44" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text up 
    vTcl:DefineAlias "$top.but45" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text down 
    vTcl:DefineAlias "$top.but46" "Button1_1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {nod +} 
    vTcl:DefineAlias "$top.but47" "Button1_2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {nod -} 
    vTcl:DefineAlias "$top.but48" "Button1_3" vTcl:WidgetProc "Toplevel1" 1
    button $top.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {rot -} 
    vTcl:DefineAlias "$top.but50" "Button1_5" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent51 \
        -background #c3c3c3 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 74 
    vTcl:DefineAlias "$top.ent51" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent52 \
        -background #c3c3c3 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 74 
    vTcl:DefineAlias "$top.ent52" "Entry1_6" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent53 \
        -background #c3c3c3 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 74 
    vTcl:DefineAlias "$top.ent53" "Entry1_7" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent54 \
        -background #c3c3c3 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c0c0c0 \
        -selectforeground black -width 64 
    vTcl:DefineAlias "$top.ent54" "Entry1_8" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab55 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -text {Single stepper mode} 
    vTcl:DefineAlias "$top.lab55" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent56 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 
    vTcl:DefineAlias "$top.ent56" "Entry1_9" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab57 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #f0f0f0f0f0f0 -text Step 
    vTcl:DefineAlias "$top.lab57" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab58 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #f0f0f0f0f0f0 -highlightcolor black \
        -text Encoder 
    vTcl:DefineAlias "$top.lab58" "Label2_10" vTcl:WidgetProc "Toplevel1" 1
    button $top.but59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text + 
    vTcl:DefineAlias "$top.but59" "Button1_4" vTcl:WidgetProc "Toplevel1" 1
    button $top.but60 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text - 
    vTcl:DefineAlias "$top.but60" "Button1_5" vTcl:WidgetProc "Toplevel1" 1
    button $top.but61 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text + 
    vTcl:DefineAlias "$top.but61" "Button1_5" vTcl:WidgetProc "Toplevel1" 1
    button $top.but62 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text + 
    vTcl:DefineAlias "$top.but62" "Button1_5" vTcl:WidgetProc "Toplevel1" 1
    button $top.but63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text + 
    vTcl:DefineAlias "$top.but63" "Button1_5" vTcl:WidgetProc "Toplevel1" 1
    button $top.but64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text + 
    vTcl:DefineAlias "$top.but64" "Button1_5" vTcl:WidgetProc "Toplevel1" 1
    button $top.but65 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text + 
    vTcl:DefineAlias "$top.but65" "Button1_5" vTcl:WidgetProc "Toplevel1" 1
    button $top.but66 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text - 
    vTcl:DefineAlias "$top.but66" "Button1_6" vTcl:WidgetProc "Toplevel1" 1
    button $top.but67 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text - 
    vTcl:DefineAlias "$top.but67" "Button1_6" vTcl:WidgetProc "Toplevel1" 1
    button $top.but68 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text - 
    vTcl:DefineAlias "$top.but68" "Button1_6" vTcl:WidgetProc "Toplevel1" 1
    button $top.but69 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text - 
    vTcl:DefineAlias "$top.but69" "Button1_6" vTcl:WidgetProc "Toplevel1" 1
    button $top.but70 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text - 
    vTcl:DefineAlias "$top.but70" "Button1_6" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent71 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 
    vTcl:DefineAlias "$top.ent71" "Entry1_7" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent72 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 
    vTcl:DefineAlias "$top.ent72" "Entry1_8" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent73 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 
    vTcl:DefineAlias "$top.ent73" "Entry1_10" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent74 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 
    vTcl:DefineAlias "$top.ent74" "Entry1_10" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent75 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 
    vTcl:DefineAlias "$top.ent75" "Entry1_10" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent76 \
        -background #c3c3c3 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 
    vTcl:DefineAlias "$top.ent76" "Entry1_10" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent77 \
        -background #c3c3c3 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 
    vTcl:DefineAlias "$top.ent77" "Entry1_10" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent78 \
        -background #c3c3c3 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 
    vTcl:DefineAlias "$top.ent78" "Entry1_10" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent79 \
        -background #c3c3c3 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 
    vTcl:DefineAlias "$top.ent79" "Entry1_10" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent80 \
        -background #c3c3c3 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 
    vTcl:DefineAlias "$top.ent80" "Entry1_10" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab81 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #f0f0f0f0f0f0 -highlightcolor black -text Step 
    vTcl:DefineAlias "$top.lab81" "Label2_11" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab82 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #f0f0f0f0f0f0 -highlightcolor black \
        -text Encoder 
    vTcl:DefineAlias "$top.lab82" "Label2_11" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent83 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 74 
    vTcl:DefineAlias "$top.ent83" "Entry1_12" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent84 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 74 
    vTcl:DefineAlias "$top.ent84" "Entry1_13" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent85 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 74 
    vTcl:DefineAlias "$top.ent85" "Entry1_14" vTcl:WidgetProc "Toplevel1" 1
    button $top.but86 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {axis definition} 
    vTcl:DefineAlias "$top.but86" "Button1_4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab87 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #f0f0f0f0f0f0 -highlightcolor black -text rot 
    vTcl:DefineAlias "$top.lab87" "Label2_5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab88 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #f0f0f0f0f0f0 -highlightcolor black -text z 
    vTcl:DefineAlias "$top.lab88" "Label2_6" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab89 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #f0f0f0f0f0f0 -highlightcolor black -text nod 
    vTcl:DefineAlias "$top.lab89" "Label2_7" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.m90
    menu $site_3_0 \
        -activebackground SystemHighlight \
        -activeforeground SystemHighlightText \
        -background $vTcl(pr,menubgcolor) -font TkDefaultFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    button $top.but91 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {rot +} 
    vTcl:DefineAlias "$top.but91" "Button1_6" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can44 \
        -in $top -x 290 -y 10 -width 407 -relwidth 0 -height 350 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 42 -y 239 -width 57 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 42 -y 287 -width 57 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 130 -y 260 -width 57 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 190 -y 260 -width 57 -height 44 -anchor nw \
        -bordermode ignore 
    place $top.but50 \
        -in $top -x 80 -y 160 -width 57 -height 44 -anchor nw \
        -bordermode ignore 
    place $top.ent51 \
        -in $top -x 160 -y 30 -width 74 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent52 \
        -in $top -x 160 -y 60 -width 74 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent53 \
        -in $top -x 160 -y 90 -width 74 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 850 -y 100 -width 64 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 720 -y 30 -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 780 -y 100 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.lab57 \
        -in $top -x 790 -y 70 -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 830 -y 70 -width 116 -relwidth 0 -height 26 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but59 \
        -in $top -x 710 -y 100 -width 27 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but60 \
        -in $top -x 740 -y 100 -width 27 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but61 \
        -in $top -x 710 -y 130 -width 27 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but62 \
        -in $top -x 710 -y 160 -width 27 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but63 \
        -in $top -x 710 -y 190 -width 27 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but64 \
        -in $top -x 710 -y 220 -width 27 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but65 \
        -in $top -x 710 -y 250 -width 27 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but66 \
        -in $top -x 740 -y 130 -width 27 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but67 \
        -in $top -x 740 -y 160 -width 27 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but68 \
        -in $top -x 740 -y 190 -width 27 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but69 \
        -in $top -x 740 -y 220 -width 27 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but70 \
        -in $top -x 740 -y 250 -width 27 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.ent71 \
        -in $top -x 780 -y 130 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent72 \
        -in $top -x 780 -y 160 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent73 \
        -in $top -x 780 -y 190 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent74 \
        -in $top -x 780 -y 220 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent75 \
        -in $top -x 780 -y 250 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent76 \
        -in $top -x 850 -y 130 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent77 \
        -in $top -x 850 -y 160 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent78 \
        -in $top -x 850 -y 190 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent79 \
        -in $top -x 850 -y 220 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent80 \
        -in $top -x 850 -y 250 -width 64 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.lab81 \
        -in $top -x 100 -y 0 -width 36 -height 26 -anchor nw \
        -bordermode ignore 
    place $top.lab82 \
        -in $top -x 160 -y 0 -width 76 -relwidth 0 -height 26 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent83 \
        -in $top -x 80 -y 30 -width 74 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent84 \
        -in $top -x 80 -y 60 -width 74 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent85 \
        -in $top -x 80 -y 90 -width 74 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.but86 \
        -in $top -x 780 -y 340 -width 147 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab87 \
        -in $top -x 40 -y 30 -width 36 -height 26 -anchor nw \
        -bordermode ignore 
    place $top.lab88 \
        -in $top -x 40 -y 60 -width 36 -height 26 -anchor nw \
        -bordermode ignore 
    place $top.lab89 \
        -in $top -x 40 -y 90 -width 36 -height 26 -anchor nw \
        -bordermode ignore 
    place $top.but91 \
        -in $top -x 20 -y 160 -width 57 -height 44 -anchor nw \
        -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

