#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Mar 05, 2020 03:40:48 PM CET  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 931x287+656+143
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    button $top.but44 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5b5b5b -command yplus_increment \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text y+ 
    vTcl:DefineAlias "$top.but44" "yplus" vTcl:WidgetProc "Toplevel1" 1
    button $top.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5b5b5b -command yminus_increment \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text y- 
    vTcl:DefineAlias "$top.but45" "yminus" vTcl:WidgetProc "Toplevel1" 1
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5b5b5b -command xplus_increment \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text x+ 
    vTcl:DefineAlias "$top.but46" "xplus" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5b5b5b -command xminus_increment \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text x- 
    vTcl:DefineAlias "$top.but47" "xminus" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex49 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 -wrap word 
    .top42.tex49 configure -font "TkTextFont"
    .top42.tex49 insert end text
    vTcl:DefineAlias "$top.tex49" "dx" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text x 
    vTcl:DefineAlias "$top.lab50" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text theta 
    vTcl:DefineAlias "$top.lab52" "Label1_4" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex53 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 -wrap word 
    .top42.tex53 configure -font "TkTextFont"
    .top42.tex53 insert end text
    vTcl:DefineAlias "$top.tex53" "dy" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex54 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 -wrap word 
    .top42.tex54 configure -font "TkTextFont"
    .top42.tex54 insert end text
    vTcl:DefineAlias "$top.tex54" "dtheta" vTcl:WidgetProc "Toplevel1" 1
    button $top.but56 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5b5b5b -command yplus_increment \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text x+ 
    vTcl:DefineAlias "$top.but56" "xplus_7" vTcl:WidgetProc "Toplevel1" 1
    button $top.but57 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5b5b5b -command thetaplus_increment \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text ccw 
    vTcl:DefineAlias "$top.but57" "ccw" vTcl:WidgetProc "Toplevel1" 1
    button $top.but58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5b5b5b -command thetaminus_increment \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text cw 
    vTcl:DefineAlias "$top.but58" "cw" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab59 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text y 
    vTcl:DefineAlias "$top.lab59" "Label1_10" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab60 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text step 
    vTcl:DefineAlias "$top.lab60" "Label1_11" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab61 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text position 
    vTcl:DefineAlias "$top.lab61" "Label1_12" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex62 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 -wrap word 
    .top42.tex62 configure -font "TkTextFont"
    .top42.tex62 insert end text
    vTcl:DefineAlias "$top.tex62" "xPos" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex63 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 -wrap word 
    .top42.tex63 configure -font "TkTextFont"
    .top42.tex63 insert end text
    vTcl:DefineAlias "$top.tex63" "yPos" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex64 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 -wrap word 
    .top42.tex64 configure -font "TkTextFont"
    .top42.tex64 insert end text
    vTcl:DefineAlias "$top.tex64" "thetaPos" vTcl:WidgetProc "Toplevel1" 1
    button $top.but65 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5b5b5b -command yplus_increment \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text menu 
    vTcl:DefineAlias "$top.but65" "menu" vTcl:WidgetProc "Toplevel1" 1
    button $top.but66 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5b5b5b -command call_mappingmenu \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text mapping 
    vTcl:DefineAlias "$top.but66" "mappingMenu" vTcl:WidgetProc "Toplevel1" 1
    button $top.but68 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text <> 
    vTcl:DefineAlias "$top.but68" "refresh" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab69 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Status 
    vTcl:DefineAlias "$top.lab69" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab70 \
        -activebackground #f9f9f9 -activeforeground black -background #26d96d \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text connected 
    vTcl:DefineAlias "$top.lab70" "statusLabel" vTcl:WidgetProc "Toplevel1" 1
    button $top.but43 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #eb0214 -command stop_motors -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text STOP 
    vTcl:DefineAlias "$top.but43" "stop" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex44 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 -wrap word 
    .top42.tex44 configure -font "TkTextFont"
    .top42.tex44 insert end text
    vTcl:DefineAlias "$top.tex44" "dz" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex45 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 -wrap word 
    .top42.tex45 configure -font "TkTextFont"
    .top42.tex45 insert end text
    vTcl:DefineAlias "$top.tex45" "zPos" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text z 
    vTcl:DefineAlias "$top.lab46" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5b5b5b -command zplus_increment \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text z+ 
    vTcl:DefineAlias "$top.but48" "zPlus" vTcl:WidgetProc "Toplevel1" 1
    button $top.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5b5b5b -command zminus_increment \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text z- 
    vTcl:DefineAlias "$top.but50" "zMinus" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex43 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 -wrap word 
    .top42.tex43 configure -font "TkTextFont"
    .top42.tex43 insert end text
    vTcl:DefineAlias "$top.tex43" "xdesired" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex46 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 -wrap word 
    .top42.tex46 configure -font "TkTextFont"
    .top42.tex46 insert end text
    vTcl:DefineAlias "$top.tex46" "ydesired" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex47 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 -wrap word 
    .top42.tex47 configure -font "TkTextFont"
    .top42.tex47 insert end text
    vTcl:DefineAlias "$top.tex47" "zdesired" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex48 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 64 -wrap word 
    .top42.tex48 configure -font "TkTextFont"
    .top42.tex48 insert end text
    vTcl:DefineAlias "$top.tex48" "thetadesired" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {go to} 
    vTcl:DefineAlias "$top.lab49" "Label1_2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5b5b5b -command go_x -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text go 
    vTcl:DefineAlias "$top.but51" "gox" vTcl:WidgetProc "Toplevel1" 1
    button $top.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5b5b5b -command go_y -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text go 
    vTcl:DefineAlias "$top.but52" "goy" vTcl:WidgetProc "Toplevel1" 1
    button $top.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5b5b5b -command go_z -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text go 
    vTcl:DefineAlias "$top.but53" "goz" vTcl:WidgetProc "Toplevel1" 1
    button $top.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5b5b5b -command go_theta -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text go 
    vTcl:DefineAlias "$top.but54" "gotheta" vTcl:WidgetProc "Toplevel1" 1
    button $top.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5b5b5b -command go_all -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {go all} 
    vTcl:DefineAlias "$top.but55" "goall" vTcl:WidgetProc "Toplevel1" 1
    button $top.but59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5b5b5b -command traj_plus -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {traj +} 
    vTcl:DefineAlias "$top.but59" "trajminus" vTcl:WidgetProc "Toplevel1" 1
    button $top.but60 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5b5b5b -command traj_minus -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {traj -} 
    vTcl:DefineAlias "$top.but60" "trajplus" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but44 \
        -in $top -x 400 -y 80 -width 67 -relwidth 0 -height 64 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 400 -y 200 -width 67 -height 64 -anchor nw \
        -bordermode ignore 
    place $top.but46 \
        -in $top -x 490 -y 130 -width 67 -height 64 -anchor nw \
        -bordermode ignore 
    place $top.but47 \
        -in $top -x 310 -y 130 -width 67 -height 64 -anchor nw \
        -bordermode ignore 
    place $top.tex49 \
        -in $top -x 640 -y 50 -width 64 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 580 -y 50 -width 54 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 580 -y 140 -width 54 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.tex53 \
        -in $top -x 640 -y 80 -width 64 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.tex54 \
        -in $top -x 640 -y 140 -width 64 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but56 \
        -in $top -x -150 -y 90 -width 67 -height 64 -anchor nw \
        -bordermode ignore 
    place $top.but57 \
        -in $top -x 140 -y 110 -width 67 -height 64 -anchor nw \
        -bordermode ignore 
    place $top.but58 \
        -in $top -x 140 -y 180 -width 67 -height 64 -anchor nw \
        -bordermode ignore 
    place $top.lab59 \
        -in $top -x 580 -y 80 -width 54 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab60 \
        -in $top -x 640 -y 20 -width 54 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab61 \
        -in $top -x 730 -y 20 -width 74 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex62 \
        -in $top -x 730 -y 50 -width 64 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.tex63 \
        -in $top -x 730 -y 80 -width 64 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.tex64 \
        -in $top -x 730 -y 140 -width 64 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but65 \
        -in $top -x 800 -y 250 -width 127 -relwidth 0 -height 34 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but66 \
        -in $top -x 800 -y 220 -width 127 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.but68 \
        -in $top -x 90 -y 240 -anchor nw -bordermode ignore 
    place $top.lab69 \
        -in $top -x 10 -y 200 -anchor nw -bordermode ignore 
    place $top.lab70 \
        -in $top -x 10 -y 230 -width 64 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but43 \
        -in $top -x 20 -y 10 -width 97 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex44 \
        -in $top -x 640 -y 110 -width 64 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.tex45 \
        -in $top -x 730 -y 110 -width 64 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.lab46 \
        -in $top -x 580 -y 110 -width 54 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.but48 \
        -in $top -x 230 -y 10 -width 67 -height 64 -anchor nw \
        -bordermode ignore 
    place $top.but50 \
        -in $top -x 230 -y 90 -width 67 -height 64 -anchor nw \
        -bordermode ignore 
    place $top.tex43 \
        -in $top -x 815 -y 50 -width 64 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.tex46 \
        -in $top -x 815 -y 80 -width 64 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.tex47 \
        -in $top -x 815 -y 110 -width 64 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.tex48 \
        -in $top -x 815 -y 140 -width 64 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.lab49 \
        -in $top -x 810 -y 14 -width 74 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 880 -y 50 -width 37 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 880 -y 80 -width 37 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but53 \
        -in $top -x 880 -y 110 -width 37 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but54 \
        -in $top -x 880 -y 140 -width 37 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but55 \
        -in $top -x 860 -y 170 -width 57 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but59 \
        -in $top -x 690 -y 220 -width 57 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but60 \
        -in $top -x 630 -y 220 -width 57 -height 44 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

