#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Mar 18, 2020 01:13:42 PM CET  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m52" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1243x564+417+202
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 5764 1452
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 18} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Pc: 
    vTcl:DefineAlias "$top.lab43" "Ppc" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 18} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {not connected} 
    vTcl:DefineAlias "$top.lab44" "Ppcdisp" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 18} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Mc: 
    vTcl:DefineAlias "$top.lab45" "Pmc" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 18} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {not connected} 
    vTcl:DefineAlias "$top.lab46" "Pmcdisp" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe48
    vTcl:DefineAlias "$top.tSe48" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 18} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text MBE: 
    vTcl:DefineAlias "$top.lab49" "PMBE" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe50
    vTcl:DefineAlias "$top.tSe50" "TSeparator1_5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 18} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {not connected} 
    vTcl:DefineAlias "$top.lab51" "PMBEdisp" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.m52
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ttk::separator $top.tSe53
    vTcl:DefineAlias "$top.tSe53" "TSeparator1_7" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 18} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text LL: 
    vTcl:DefineAlias "$top.lab54" "PLL" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 18} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {not connected} 
    vTcl:DefineAlias "$top.lab55" "PLLdisp" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra56 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 395 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 705 
    vTcl:DefineAlias "$top.fra56" "Graphframe" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent57 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent57" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab58 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 12} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Polltime 
    vTcl:DefineAlias "$top.lab58" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -command setPolltime -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text set 
    vTcl:DefineAlias "$top.but59" "set polltime" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton $top.tCh60 \
        -variable Mccheck -takefocus {} -text Mc 
    vTcl:DefineAlias "$top.tCh60" "ckMc" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton $top.tCh61 \
        -variable Pcchk -takefocus {} -text Pc 
    vTcl:DefineAlias "$top.tCh61" "ckPc" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton $top.tCh62 \
        -variable MBEchk -takefocus {} -text MBE 
    vTcl:DefineAlias "$top.tCh62" "ckMBE" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton $top.tCh63 \
        -variable LLchk -takefocus {} -text LL 
    vTcl:DefineAlias "$top.tCh63" "ckLL" vTcl:WidgetProc "Toplevel1" 1
    button $top.but64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #5f5f5f -disabledforeground #5f5f5f \
        -font {-family {Comic Sans MS} -size 12} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Menu 
    vTcl:DefineAlias "$top.but64" "Menu" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab65 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 18} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Lamp: 
    vTcl:DefineAlias "$top.lab65" "PHe" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab66 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 18} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {not connected} 
    vTcl:DefineAlias "$top.lab66" "PHedisp" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab67 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 18} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Forevac 1:} 
    vTcl:DefineAlias "$top.lab67" "PP1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab68 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 18} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {not connected} 
    vTcl:DefineAlias "$top.lab68" "PP1disp" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab69 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 18} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Forevac 2:} 
    vTcl:DefineAlias "$top.lab69" "PP2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab70 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Comic Sans MS} -size 18} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {not connected} 
    vTcl:DefineAlias "$top.lab70" "PP2disp" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton $top.tCh71 \
        -variable Lampchk -takefocus {} -text Lamp 
    vTcl:DefineAlias "$top.tCh71" "ckLamp" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton $top.tCh72 \
        -variable Fore1chk -takefocus {} -text Fore1 
    vTcl:DefineAlias "$top.tCh72" "ckFore1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton $top.tCh73 \
        -variable Fore2chk -takefocus {} -text Fore2 
    vTcl:DefineAlias "$top.tCh73" "ckFore2" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 35 -width 705 
    vTcl:DefineAlias "$top.fra43" "Toolbarframe" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 30 -y 100 -width 94 -relwidth 0 -height 71 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 150 -y 100 -width 284 -relwidth 0 -height 71 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 30 -y 20 -width 94 -height 71 -anchor nw \
        -bordermode ignore 
    place $top.lab46 \
        -in $top -x 150 -y 30 -width 284 -height 71 -anchor nw \
        -bordermode ignore 
    place $top.tSe48 \
        -in $top -x 60 -y 100 -width 360 -anchor nw -bordermode inside 
    place $top.lab49 \
        -in $top -x 40 -y 190 -width 94 -height 71 -anchor nw \
        -bordermode ignore 
    place $top.tSe50 \
        -in $top -x 60 -y 180 -width 360 -height 2 -anchor nw \
        -bordermode ignore 
    place $top.lab51 \
        -in $top -x 150 -y 190 -width 284 -height 71 -anchor nw \
        -bordermode ignore 
    place $top.tSe53 \
        -in $top -x 60 -y 260 -width 360 -height 2 -anchor nw \
        -bordermode ignore 
    place $top.lab54 \
        -in $top -x 40 -y 270 -width 94 -height 71 -anchor nw \
        -bordermode ignore 
    place $top.lab55 \
        -in $top -x 150 -y 270 -width 284 -height 71 -anchor nw \
        -bordermode ignore 
    place $top.fra56 \
        -in $top -x 490 -y 10 -width 705 -relwidth 0 -height 395 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent57 \
        -in $top -x 970 -y 460 -width 84 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 900 -y 453 -width 63 -height 29 -anchor nw \
        -bordermode ignore 
    place $top.but59 \
        -in $top -x 1070 -y 460 -anchor nw -bordermode ignore 
    place $top.tCh60 \
        -in $top -x 490 -y 470 -anchor nw -bordermode ignore 
    place $top.tCh61 \
        -in $top -x 550 -y 470 -width 40 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.tCh62 \
        -in $top -x 600 -y 470 -width 50 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCh63 \
        -in $top -x 660 -y 470 -width 50 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.but64 \
        -in $top -x 1110 -y 460 -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 60 -y 420 -width 94 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 150 -y 420 -width 284 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab67 \
        -in $top -x 20 -y 470 -width 114 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab68 \
        -in $top -x 150 -y 470 -width 284 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab69 \
        -in $top -x 20 -y 510 -width 114 -height 51 -anchor nw \
        -bordermode ignore 
    place $top.lab70 \
        -in $top -x 150 -y 510 -width 284 -height 51 -anchor nw \
        -bordermode ignore 
    place $top.tCh71 \
        -in $top -x 710 -y 470 -width 60 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCh72 \
        -in $top -x 780 -y 470 -width 60 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.tCh73 \
        -in $top -x 490 -y 500 -width 60 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.fra43 \
        -in $top -x 490 -y 410 -width 705 -relwidth 0 -height 35 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

