#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Mar 18, 2020 10:48:59 PM CET  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Pressures_better_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    Pressures_better_support.set_Tk_var()
    top = Toplevel1 (root)
    Pressures_better_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    Pressures_better_support.set_Tk_var()
    top = Toplevel1 (w)
    Pressures_better_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1243x564+417+202")
        top.minsize(120, 1)
        top.maxsize(5764, 1452)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Ppc = tk.Label(top)
        self.Ppc.place(relx=0.024, rely=0.177, height=71, width=94)
        self.Ppc.configure(activebackground="#f9f9f9")
        self.Ppc.configure(activeforeground="black")
        self.Ppc.configure(background="#d9d9d9")
        self.Ppc.configure(disabledforeground="#a3a3a3")
        self.Ppc.configure(font="-family {Comic Sans MS} -size 18")
        self.Ppc.configure(foreground="#000000")
        self.Ppc.configure(highlightbackground="#d9d9d9")
        self.Ppc.configure(highlightcolor="black")
        self.Ppc.configure(text='''Pc:''')

        self.Ppcdisp = tk.Label(top)
        self.Ppcdisp.place(relx=0.121, rely=0.177, height=71, width=284)
        self.Ppcdisp.configure(activebackground="#f9f9f9")
        self.Ppcdisp.configure(activeforeground="black")
        self.Ppcdisp.configure(background="#d9d9d9")
        self.Ppcdisp.configure(disabledforeground="#a3a3a3")
        self.Ppcdisp.configure(font="-family {Comic Sans MS} -size 18")
        self.Ppcdisp.configure(foreground="#000000")
        self.Ppcdisp.configure(highlightbackground="#d9d9d9")
        self.Ppcdisp.configure(highlightcolor="black")
        self.Ppcdisp.configure(text='''not connected''')

        self.Pmc = tk.Label(top)
        self.Pmc.place(relx=0.024, rely=0.035, height=71, width=94)
        self.Pmc.configure(activebackground="#f9f9f9")
        self.Pmc.configure(activeforeground="black")
        self.Pmc.configure(background="#d9d9d9")
        self.Pmc.configure(disabledforeground="#a3a3a3")
        self.Pmc.configure(font="-family {Comic Sans MS} -size 18")
        self.Pmc.configure(foreground="#000000")
        self.Pmc.configure(highlightbackground="#d9d9d9")
        self.Pmc.configure(highlightcolor="black")
        self.Pmc.configure(text='''Mc:''')

        self.Pmcdisp = tk.Label(top)
        self.Pmcdisp.place(relx=0.121, rely=0.053, height=71, width=284)
        self.Pmcdisp.configure(activebackground="#f9f9f9")
        self.Pmcdisp.configure(activeforeground="black")
        self.Pmcdisp.configure(background="#d9d9d9")
        self.Pmcdisp.configure(disabledforeground="#a3a3a3")
        self.Pmcdisp.configure(font="-family {Comic Sans MS} -size 18")
        self.Pmcdisp.configure(foreground="#000000")
        self.Pmcdisp.configure(highlightbackground="#d9d9d9")
        self.Pmcdisp.configure(highlightcolor="black")
        self.Pmcdisp.configure(text='''not connected''')

        self.TSeparator1 = ttk.Separator(top)
        self.TSeparator1.place(relx=0.048, rely=0.177, relwidth=0.29)

        self.PMBE = tk.Label(top)
        self.PMBE.place(relx=0.032, rely=0.337, height=71, width=94)
        self.PMBE.configure(activebackground="#f9f9f9")
        self.PMBE.configure(activeforeground="black")
        self.PMBE.configure(background="#d9d9d9")
        self.PMBE.configure(disabledforeground="#a3a3a3")
        self.PMBE.configure(font="-family {Comic Sans MS} -size 18")
        self.PMBE.configure(foreground="#000000")
        self.PMBE.configure(highlightbackground="#d9d9d9")
        self.PMBE.configure(highlightcolor="black")
        self.PMBE.configure(text='''MBE:''')

        self.TSeparator1_5 = ttk.Separator(top)
        self.TSeparator1_5.place(relx=0.048, rely=0.319, relwidth=0.29)

        self.PMBEdisp = tk.Label(top)
        self.PMBEdisp.place(relx=0.121, rely=0.337, height=71, width=284)
        self.PMBEdisp.configure(activebackground="#f9f9f9")
        self.PMBEdisp.configure(activeforeground="black")
        self.PMBEdisp.configure(background="#d9d9d9")
        self.PMBEdisp.configure(disabledforeground="#a3a3a3")
        self.PMBEdisp.configure(font="-family {Comic Sans MS} -size 18")
        self.PMBEdisp.configure(foreground="#000000")
        self.PMBEdisp.configure(highlightbackground="#d9d9d9")
        self.PMBEdisp.configure(highlightcolor="black")
        self.PMBEdisp.configure(text='''not connected''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.TSeparator1_7 = ttk.Separator(top)
        self.TSeparator1_7.place(relx=0.048, rely=0.461, relwidth=0.29)

        self.PLL = tk.Label(top)
        self.PLL.place(relx=0.032, rely=0.479, height=71, width=94)
        self.PLL.configure(activebackground="#f9f9f9")
        self.PLL.configure(activeforeground="black")
        self.PLL.configure(background="#d9d9d9")
        self.PLL.configure(disabledforeground="#a3a3a3")
        self.PLL.configure(font="-family {Comic Sans MS} -size 18")
        self.PLL.configure(foreground="#000000")
        self.PLL.configure(highlightbackground="#d9d9d9")
        self.PLL.configure(highlightcolor="black")
        self.PLL.configure(text='''LL:''')

        self.PLLdisp = tk.Label(top)
        self.PLLdisp.place(relx=0.121, rely=0.479, height=71, width=284)
        self.PLLdisp.configure(activebackground="#f9f9f9")
        self.PLLdisp.configure(activeforeground="black")
        self.PLLdisp.configure(background="#d9d9d9")
        self.PLLdisp.configure(disabledforeground="#a3a3a3")
        self.PLLdisp.configure(font="-family {Comic Sans MS} -size 18")
        self.PLLdisp.configure(foreground="#000000")
        self.PLLdisp.configure(highlightbackground="#d9d9d9")
        self.PLLdisp.configure(highlightcolor="black")
        self.PLLdisp.configure(text='''not connected''')

        self.Graphframe = tk.Frame(top)
        self.Graphframe.place(relx=0.394, rely=0.018, relheight=0.7
                , relwidth=0.567)
        self.Graphframe.configure(relief='groove')
        self.Graphframe.configure(borderwidth="2")
        self.Graphframe.configure(relief="groove")
        self.Graphframe.configure(background="#d9d9d9")
        self.Graphframe.configure(highlightbackground="#d9d9d9")
        self.Graphframe.configure(highlightcolor="black")

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.78, rely=0.816,height=20, relwidth=0.068)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.724, rely=0.803, height=29, width=63)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Comic Sans MS} -size 12")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Polltime''')

        self.set_polltime = tk.Button(top)
        self.set_polltime.place(relx=0.861, rely=0.816, height=24, width=26)
        self.set_polltime.configure(activebackground="#ececec")
        self.set_polltime.configure(activeforeground="#000000")
        self.set_polltime.configure(background="#5f5f5f")
        self.set_polltime.configure(command=Pressures_better_support.setPolltime)
        self.set_polltime.configure(disabledforeground="#a3a3a3")
        self.set_polltime.configure(foreground="#000000")
        self.set_polltime.configure(highlightbackground="#d9d9d9")
        self.set_polltime.configure(highlightcolor="black")
        self.set_polltime.configure(pady="0")
        self.set_polltime.configure(text='''set''')

        self.style.map('TCheckbutton',background=
            [('selected', _bgcolor), ('active', _ana2color)])
        self.ckMc = ttk.Checkbutton(top)
        self.ckMc.place(relx=0.394, rely=0.833, relwidth=0.032, relheight=0.0
                , height=21)
        self.ckMc.configure(variable=Pressures_better_support.Mccheck)
        self.ckMc.configure(takefocus="")
        self.ckMc.configure(text='''Mc''')

        self.ckPc = ttk.Checkbutton(top)
        self.ckPc.place(relx=0.442, rely=0.833, relwidth=0.032, relheight=0.0
                , height=21)
        self.ckPc.configure(variable=Pressures_better_support.Pcchk)
        self.ckPc.configure(takefocus="")
        self.ckPc.configure(text='''Pc''')

        self.ckMBE = ttk.Checkbutton(top)
        self.ckMBE.place(relx=0.483, rely=0.833, relwidth=0.04, relheight=0.0
                , height=21)
        self.ckMBE.configure(variable=Pressures_better_support.MBEchk)
        self.ckMBE.configure(takefocus="")
        self.ckMBE.configure(text='''MBE''')

        self.ckLL = ttk.Checkbutton(top)
        self.ckLL.place(relx=0.531, rely=0.833, relwidth=0.04, relheight=0.0
                , height=21)
        self.ckLL.configure(variable=Pressures_better_support.LLchk)
        self.ckLL.configure(takefocus="")
        self.ckLL.configure(text='''LL''')

        self.Menu = tk.Button(top)
        self.Menu.place(relx=0.893, rely=0.816, height=38, width=54)
        self.Menu.configure(activebackground="#ececec")
        self.Menu.configure(activeforeground="#000000")
        self.Menu.configure(background="#5f5f5f")
        self.Menu.configure(disabledforeground="#5f5f5f")
        self.Menu.configure(font="-family {Comic Sans MS} -size 12")
        self.Menu.configure(foreground="#000000")
        self.Menu.configure(highlightbackground="#d9d9d9")
        self.Menu.configure(highlightcolor="black")
        self.Menu.configure(pady="0")
        self.Menu.configure(text='''Menu''')

        self.PHe = tk.Label(top)
        self.PHe.place(relx=0.048, rely=0.745, height=51, width=94)
        self.PHe.configure(activebackground="#f9f9f9")
        self.PHe.configure(activeforeground="black")
        self.PHe.configure(background="#d9d9d9")
        self.PHe.configure(disabledforeground="#a3a3a3")
        self.PHe.configure(font="-family {Comic Sans MS} -size 18")
        self.PHe.configure(foreground="#000000")
        self.PHe.configure(highlightbackground="#d9d9d9")
        self.PHe.configure(highlightcolor="black")
        self.PHe.configure(text='''Lamp:''')

        self.PHedisp = tk.Label(top)
        self.PHedisp.place(relx=0.121, rely=0.745, height=51, width=284)
        self.PHedisp.configure(activebackground="#f9f9f9")
        self.PHedisp.configure(activeforeground="black")
        self.PHedisp.configure(background="#d9d9d9")
        self.PHedisp.configure(disabledforeground="#a3a3a3")
        self.PHedisp.configure(font="-family {Comic Sans MS} -size 18")
        self.PHedisp.configure(foreground="#000000")
        self.PHedisp.configure(highlightbackground="#d9d9d9")
        self.PHedisp.configure(highlightcolor="black")
        self.PHedisp.configure(text='''not connected''')

        self.PP1 = tk.Label(top)
        self.PP1.place(relx=0.016, rely=0.833, height=51, width=114)
        self.PP1.configure(activebackground="#f9f9f9")
        self.PP1.configure(activeforeground="black")
        self.PP1.configure(background="#d9d9d9")
        self.PP1.configure(disabledforeground="#a3a3a3")
        self.PP1.configure(font="-family {Comic Sans MS} -size 18")
        self.PP1.configure(foreground="#000000")
        self.PP1.configure(highlightbackground="#d9d9d9")
        self.PP1.configure(highlightcolor="black")
        self.PP1.configure(text='''Forevac 1:''')

        self.PP1disp = tk.Label(top)
        self.PP1disp.place(relx=0.121, rely=0.833, height=51, width=284)
        self.PP1disp.configure(activebackground="#f9f9f9")
        self.PP1disp.configure(activeforeground="black")
        self.PP1disp.configure(background="#d9d9d9")
        self.PP1disp.configure(disabledforeground="#a3a3a3")
        self.PP1disp.configure(font="-family {Comic Sans MS} -size 18")
        self.PP1disp.configure(foreground="#000000")
        self.PP1disp.configure(highlightbackground="#d9d9d9")
        self.PP1disp.configure(highlightcolor="black")
        self.PP1disp.configure(text='''not connected''')

        self.PP2 = tk.Label(top)
        self.PP2.place(relx=0.016, rely=0.904, height=51, width=114)
        self.PP2.configure(activebackground="#f9f9f9")
        self.PP2.configure(activeforeground="black")
        self.PP2.configure(background="#d9d9d9")
        self.PP2.configure(disabledforeground="#a3a3a3")
        self.PP2.configure(font="-family {Comic Sans MS} -size 18")
        self.PP2.configure(foreground="#000000")
        self.PP2.configure(highlightbackground="#d9d9d9")
        self.PP2.configure(highlightcolor="black")
        self.PP2.configure(text='''Forevac 2:''')

        self.PP2disp = tk.Label(top)
        self.PP2disp.place(relx=0.121, rely=0.904, height=51, width=284)
        self.PP2disp.configure(activebackground="#f9f9f9")
        self.PP2disp.configure(activeforeground="black")
        self.PP2disp.configure(background="#d9d9d9")
        self.PP2disp.configure(disabledforeground="#a3a3a3")
        self.PP2disp.configure(font="-family {Comic Sans MS} -size 18")
        self.PP2disp.configure(foreground="#000000")
        self.PP2disp.configure(highlightbackground="#d9d9d9")
        self.PP2disp.configure(highlightcolor="black")
        self.PP2disp.configure(text='''not connected''')

        self.ckLamp = ttk.Checkbutton(top)
        self.ckLamp.place(relx=0.571, rely=0.833, relwidth=0.048, relheight=0.0
                , height=21)
        self.ckLamp.configure(variable=Pressures_better_support.Lampchk)
        self.ckLamp.configure(takefocus="")
        self.ckLamp.configure(text='''Lamp''')

        self.ckFore1 = ttk.Checkbutton(top)
        self.ckFore1.place(relx=0.628, rely=0.833, relwidth=0.048, relheight=0.0
                , height=21)
        self.ckFore1.configure(variable=Pressures_better_support.Fore1chk)
        self.ckFore1.configure(takefocus="")
        self.ckFore1.configure(text='''Fore1''')

        self.ckFore2 = ttk.Checkbutton(top)
        self.ckFore2.place(relx=0.394, rely=0.887, relwidth=0.048, relheight=0.0
                , height=21)
        self.ckFore2.configure(variable=Pressures_better_support.Fore2chk)
        self.ckFore2.configure(takefocus="")
        self.ckFore2.configure(text='''Fore2''')

        self.Toolbarframe = tk.Frame(top)
        self.Toolbarframe.place(relx=0.394, rely=0.727, relheight=0.062
                , relwidth=0.567)
        self.Toolbarframe.configure(relief='groove')
        self.Toolbarframe.configure(borderwidth="2")
        self.Toolbarframe.configure(relief="groove")
        self.Toolbarframe.configure(background="#d9d9d9")
        self.Toolbarframe.configure(highlightbackground="#d9d9d9")
        self.Toolbarframe.configure(highlightcolor="black")

if __name__ == '__main__':
    vp_start_gui()





