#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Feb 14, 2020 08:16:06 PM CET  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

#after all: the caller
def startMainGUI(controlBackend): # main caller
    import Pressures
    global theController 
    theController= controlBackend #tell everybody about statemashine
    Pressures.vp_start_gui()

def UpdatePressures(pressures,names):
    text = ""
    for p, n in zip(pressures, names):
        #print(n)
        text = text + str(n) + " -  " + str(p) + " mBar " 
    #w.Display.delete('1.0',tk.END)
    #print('PressureUpdate')
    #sys.stdout.flush()
    w.Display.config(text=text)
    #print('beep')


def Graph():
    print('Pressures_support.Graph')
    sys.stdout.flush()

def Settings():
    print('Pressures_support.Settings')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    root.after(1000,theController.PressureCallRepeater) #added to start continuous read
    print("here?")

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Pressures
    Pressures.vp_start_gui()




